# Generated by Django 4.1 on 2022-08-22 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Trainee', 'Trainee')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('sallary_max', models.IntegerField(null=True)),
                ('sallary_min', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('Hiring', 'Hiring'), ('Stopped', 'Stopped')], default='Hiring', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Viewed', 'Viewed'), ('Rejected', 'Rejected'), ('Selected', 'Selected')], default='Applied', max_length=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_skills', to='jobs.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.skill')),
            ],
            options={
                'ordering': ['job', 'skill'],
                'unique_together': {('job', 'skill')},
            },
        ),
    ]
