# Generated by Django 4.1 on 2022-08-30 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_application_options_alter_application_job_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='sallary_max',
            new_name='salary_max',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='sallary_min',
            new_name='salary_min',
        ),
        migrations.AddField(
            model_name='application',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
