# Generated by Django 4.1 on 2022-08-31 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_sallary_max_job_salary_max_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='salary_max',
            new_name='salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_min',
        ),
    ]
